<?php
namespace app\admin\controller;
use app\BaseController;
use think\App;
use think\exception\HttpResponseException;

class AdminBase extends BaseController{
    protected $adminUser = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 判断是否登录
     * @return bool
     */
    public function isLogin(){
        $this->adminUser = session(config('admin.session_admin'));

        if (empty($this->adminUser)){
            return false;
        }
        return true;
    }
    // 重定向
    public function redirect(...$args){
        throw new HttpResponseException(redirect(...$args));
    }
}